-- DO NOT EDIT THIS FILE !!!
-- Set package pack for ./lua/...
package.path = package.path .. ";../lua/?.lua"

-- Welcome print
print( "Lua version: ".._VERSION.. ". Loading Lua modules ..." )

-- Loading Lua modules
-- Core = require("core.Core")


local obj = TestModel(42)
print(obj:get())    -- 42
obj:set(-1.5)
print(obj:get())    -- -1.5

-- ....
-- return Core
-- EOF