-- DO NOT EDIT THIS FILE !!!
-- Set package pack for ./lua/...
package.path = package.path .. ";../lua/?.lua"

-- Welcome print
-- print( "Lua version: ".._VERSION.. ". Loading Lua modules ..." )

-- Loading Lua modules
-- Core = require("core.Core")

-- print("main.lua loaded")


-- TestModel from c++
-- local obj = TestModel(42)
-- print("TestModel - get() = " .. obj:get())    -- 42
-- obj:set(-1.5)
-- print("TestModel - get() = " .. obj:get())    -- -1.5




sprite = CreateSprite()
MoveSprite(sprite, 2, 5)





-- EOF